[package]
name = "file_dialog"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arboard = "3.2.1"
eframe = "0.22.0"
egui = "0.22.0"
image = "0.24.7"
rfd = "0.11.4"
